.gitignore
attentive-android-sdk/src/main/java/com/attentive/androidsdk/AttentiveConfig.java
attentive-android-sdk/src/main/java/com/attentive/androidsdk/ParameterValidation.java
attentive-android-sdk/src/main/java/com/attentive/androidsdk/UserIdentifiers.java
example/src/main/java/com/attentive/example/activities/LoadCreativeActivity.java

* Adds `UserIdentifiers` param to `AttentiveConfig.identify` method. `UserIdentifiers` requires a `userAppId`. All other identifiers are optional.
* Updates `identify` to allow merging of `UserIdentifiers` if they have the same `userAppId`.
* Adds an `AttentiveConfig.clearUser` method

Updates config with optional identifiers and clear method

---

.gitignore
attentive-android-sdk/build.gradle
attentive-android-sdk/src/androidTest/java/com/attentive/androidsdk/ExampleInstrumentedTest.java
attentive-android-sdk/src/test/java/com/attentive/androidsdk/AttentiveConfigTest.java

* Adds `test` and `androidTest` directories to project and to `gradle`
* Adds sample tests

Creates Android test directories

---

attentive-android-sdk/src/main/java/com/attentive/androidsdk/VisitorService.java

fix visitor id

---

example/src/main/AndroidManifest.xml
example/src/main/java/com/attentive/example/activities/MainActivity.java
example/src/main/java/com/attentive/example/activities/ProductPageActivity.java
example/src/main/res/layout/activity_main.xml
example/src/main/res/layout/activity_product_page.xml
example/src/main/res/values/strings.xml

Adds a new screen in the UI that demos `purchase` and `add to cart` events

Adds purchase UI to the Example app

---

attentive-android-sdk/src/main/java/com/attentive/androidsdk/creatives/Creative.java
attentive-android-sdk/src/main/java/com/attentive/androidsdk/internal/network/OrderConfirmedMetadataDto.java
attentive-android-sdk/src/main/java/com/attentive/androidsdk/internal/util/ObjectToRawJsonStringConverter.java
attentive-android-sdk/src/test/java/com/attentive/androidsdk/ObjectToRawJsonStringConverterTest.java

- ObjectToRawJsonStringConverter unit tests
- move public methods to the top of Creative.java

ObjectToRawJsonStringConverter unit tests

---

attentive-android-sdk/src/test/java/com/attentive/androidsdk/AttentiveConfigTest.java

unit tests for AttentiveConfig

unit tests for AttentiveConfig

---

attentive-android-sdk/src/test/java/com/attentive/androidsdk/UserIdentifiersTest.java

unit tests for UserIdentifiers

unit tests for UserIdentifiers

---

attentive-android-sdk/src/test/java/com/attentive/androidsdk/ParameterValidationTest.java

unit tests for ParameterValidation

unit tests for ParameterValidation

---

example-kotlin/build.gradle

Updates Kotlin app to optionally use the SDK from Maven

Updates Kotlin app to optionally use the SDK from Maven

---

example/build.gradle
example/src/androidTest/java/com/attentive/example/CreativeTest.java
example/src/androidTest/java/com/attentive/example/CreativeUITest.java
example/src/main/java/com/attentive/example/ExampleApp.java
example/src/main/java/com/attentive/example/activities/MainActivity.java
example/src/main/res/layout/activity_load_creative.xml
example/src/main/res/layout/activity_main.xml
example/src/main/res/values/strings.xml

- add UI tests
- enable updating the mode without restarting the app

Add UI Tests

---

example/src/androidTest/java/com/attentive/example/CreativeUITest.java
example/src/main/java/com/attentive/example/ExampleApp.java
example/src/main/java/com/attentive/example/activities/LoadCreativeActivity.java
example/src/main/java/com/attentive/example/activities/MainActivity.java
example/src/main/res/layout/activity_main.xml
example/src/main/res/values/strings.xml

dynamically set domain and mode in UI tests

dynamically set domain and mode in UI tests

---

example/src/androidTest/java/com/attentive/example/CreativeUITest.java

- Add some more waits
- only check for SMS app open locally
- increase timeout for privacy page

Update UI Tests for AWS Device Farm

---

attentive-android-sdk/src/main/java/com/attentive/androidsdk/AttentiveApi.java
attentive-android-sdk/src/main/java/com/attentive/androidsdk/AttentiveConfig.java
attentive-android-sdk/src/main/java/com/attentive/androidsdk/internal/events/InfoEvent.java
attentive-android-sdk/src/test/java/com/attentive/androidsdk/AttentiveApiTest.java
attentive-android-sdk/src/test/java/com/attentive/androidsdk/AttentiveConfigTest.java

* Sends an INFO event when the `AttentiveConfig` is created. This will send the SDK version and the OS version to our servers.

Sends INFO event

---

attentive-android-sdk/src/androidTest/java/com/attentive/androidsdk/AttentiveApiTestIT.java
attentive-android-sdk/src/main/java/com/attentive/androidsdk/AttentiveApi.java
attentive-android-sdk/src/main/java/com/attentive/androidsdk/events/CustomEvent.java
attentive-android-sdk/src/main/java/com/attentive/androidsdk/internal/network/CustomEventMetadataDto.java
attentive-android-sdk/src/test/java/com/attentive/androidsdk/AttentiveApiTest.java
example/src/main/java/com/attentive/example/activities/ProductPageActivity.java
example/src/main/res/layout/activity_product_page.xml
example/src/main/res/values/strings.xml

* Adds CustomEvent as a new event type
* Adds button to the product page to send a custom event

Adds CustomEvent

---

attentive-android-sdk/src/main/java/com/attentive/androidsdk/creatives/Creative.java

[JIRA Card](https://attentivemobile.atlassian.net/browse/APP-2874)
This PR aims to handle the case when the user of the SDK attempts to trigger a creative while another one is already being shown. Before you would get an intermittent creative while the second one was being loaded, now it will just show the one that was being presented until now.
This feature change comes from how iOS SDK is working so it's done to achieve parity in functionality between both platforms.

[APP-2874] Exit gracefully from already displayed creative

---

README.md
attentive-android-sdk/src/main/java/com/attentive/androidsdk/AttentiveConfig.java
attentive-android-sdk/src/test/java/com/attentive/androidsdk/AttentiveConfigTest.java
example-kotlin/src/main/java/com/attentive/example_kotlin/activities/MainActivity.kt
example-kotlin/src/main/res/layout/activity_main.xml
example/src/main/java/com/attentive/example/activities/MainActivity.java
example/src/main/res/layout/activity_main.xml

* This PR has the changes to expose a functionality to allow the developers to change the domain while the app is running. There are a couple of safeguards but the change is straight forward.
* There are a couple of changes on the Readme to update the documentation on how to use this new functionality and also on the example apps to allow adding new feature examples more easily.
[JIRA Card](https://attentivemobile.atlassian.net/browse/APP-2871)
https://github.com/attentive-mobile/attentive-android-sdk/assets/169667919/199a580b-42d5-43bf-9b93-8ef2dccb1490

[APP-2871]: Add API to allow domain change while the app is running

---

attentive-android-sdk/build.gradle
attentive-android-sdk/src/main/AndroidManifest.xml
attentive-android-sdk/src/main/java/com/attentive/androidsdk/PersistentStorage.java
attentive-android-sdk/src/main/java/com/attentive/androidsdk/creatives/Creative.java
build.gradle
example-kotlin/src/main/java/com/attentive/example_kotlin/ExampleKotlinApp.kt
example/build.gradle
example/src/androidTest/java/com/attentive/example/CreativeUITest.java
example/src/androidTest/java/com/attentive/example/ForceLocaleRule.java
example/src/main/AndroidManifest.xml
example/src/main/java/com/attentive/example/activities/LoadCreativeActivity.java
example/src/main/res/layout/activity_load_creative.xml
gradle/wrapper/gradle-wrapper.properties

[JIRA Ticket](https://attentivemobile.atlassian.net/browse/APP-2870)
On this PR there are several small changes to increase the reliability of the UI test suite running on AWS. It currently sits at 99% pass rate. There is one pending issue that stops the creative from showing on larger screens so I had to also disable some of the devices on the device farm to stop them from failing.

[APP-2870]: Update test suite to make it updated and more reliable on device farm

---

README.md

Update README to include information about CustomEvent

Update README to include information about CustomEvent

---

attentive-android-sdk/src/main/java/com/attentive/androidsdk/creatives/Creative.kt
attentive-android-sdk/src/test/java/com/attentive/androidsdk/CreativeStateTest.kt
attentive-android-sdk/src/test/java/com/attentive/androidsdk/TimberTestRule.kt
example-kotlin/build.gradle
example-kotlin/src/main/java/com/attentive/example_kotlin/ExampleKotlinApp.kt

Improve creative state tests, improve visibility modifiers for internal usage vs public usage, make webview and handler injectable for better tests.

NATV-11 Add more tests for creative state

---

README.md
attentive-android-sdk/gradle.properties
attentive-android-sdk/src/main/java/com/attentive/androidsdk/AttentiveConfig.kt
attentive-android-sdk/src/main/java/com/attentive/androidsdk/AttentiveConfigInterface.kt
attentive-android-sdk/src/main/java/com/attentive/androidsdk/AttentiveSdk.kt
attentive-android-sdk/src/main/java/com/attentive/androidsdk/push/AttentiveFirebaseMessagingService.kt
example2/src/main/java/com/attentive/example2/BonniApp.kt
example2/src/main/java/com/attentive/example2/settings/SettingsScreenComposables.kt

[NATV-73](https://attentivemobile.atlassian.net/browse/NATV-73)
[NATV-73]: https://attentivemobile.atlassian.net/browse/NATV-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NATV-73 Add notification icon to config

---

attentive-android-sdk/src/main/java/com/attentive/androidsdk/AttentiveSdk.kt
attentive-android-sdk/src/main/java/com/attentive/androidsdk/push/AttentivePush.kt
attentive-android-sdk/src/test/java/com/attentive/androidsdk/CreativeStateTest.kt

[NATV-42
](https://attentivemobile.atlassian.net/browse/NATV-42)

NATV-42 Show images in rich notifications
